# ***DATA 3500*** *: Python 1*
- What is Data Science?
- Why is Python such a popular language?

## **Introduction to Python Coding**
  - The use of a # converts what you type to comments.

In [3]:
# Display the text 'Welcome to DATA 3500.'

'Welcome to DATA 3500.'

'Welcome to DATA 3500.'

In [4]:
# We can also use print() to display whatever is in the parentheses.

print('Welcome to DATA 3500.')

Welcome to DATA 3500.


In [5]:
# Python can also be used as a simple calculator.

5 / 8

0.625

In [6]:
# What happens when we try to display multiple lines of output at one time?

5 / 8
7 + 10

17

In [7]:
# We can utilize print() to ensure all results are displayed.

print(5 / 8)
print(7 + 10)

0.625
17


In [8]:
# Be sure to use comments throughout your code to make it easier to read.

# Division
print(5 / 8)

# Addition
print(7 + 10)

0.625
17


In [9]:
# Python can do addition, subtraction, multiplication, division, but it can 
# also do more advanced calculations such as exponentiation (**), modulo (%)
# or which returns the remainder of the division.

#exponentiation

print(4 * 4 * 4)
print(4 ** 3)

#modulo

print(18 - 7 - 7)
print(18 % 7)

64
64
4
4


### **Try problem #1**

### **Try problem #2**

## **Variables and Types**

We can create variables that allow us to reuse values throughout our code. Suppose we want to create a variable for height and weight, how would we do this?

In [12]:
# Create a new variable called height and let the user know how it is measured.

height = 1.79 # meters
weight = 65.2 # kilograms

height

1.79

Calculate BMI as $$BMI = weight / height^2$$

In [13]:
# We can use the actual values or we can use the new variables.

print(65.2 / 1.79 ** 2)
print(weight / height ** 2)

20.348927936081896
20.348927936081896


### **Try problem #3**

In [15]:
# Reproducibility is very important!
# If we create all of the components of bmi in one cell we can see
# how everything works together.

height = 1.65
weight = 71.9
bmi = weight / height ** 2
bmi

26.409550045913686

In [16]:
# Change the value of height and weight to the original values (1.79 and 65.2).
# What happens?

height = 1.79
weight = 65.2
bmi = weight / height ** 2
bmi

20.348927936081896

## **Python Types**
  - float, int, str, bool

In [18]:
# What type of variable is bmi?

type(bmi)

float

In [19]:
# What is an int type?

Number_of_Years = 5
type(Number_of_Years)

int

In [20]:
# What is a data type str?
# This is Python's way of representing text.
# It can be represented with single or double quotes.

x = 'body mass index'
y = "this works too"

type(x)

str

In [21]:
# Boolean is a type that can be True or False.
# Booleans are often used for filtering data.

z = True
type(z)

bool

In [22]:
# Python data types are unique because operators behavior differently
# for different data types.

print(2+3)
print('ab' + 'cd')

5
abcd


### **Try problem #4**

### **Try problem #5**

### **Try problem #6**

### **Try problem #7**

## **Python Lists**

How do we handle many data points, such as the height of all family members? Do we really want to create a new variable for each person? What if we are talking about a class full of people? A city full? A country? Creating new variables for each observation becomes too difficult. This is where Python Lists come in.

We build lists with [a, b, c, ...]

Just as we created variable below, we can create lists. These lists can contain any type of data including other lists.

In [36]:
# Create a list of family member heights in meters.

fam = [1.73, 1.68, 1.71, 1.89]
fam

[1.73, 1.68, 1.71, 1.89]

In [37]:
# Lists can also contain different types of data within a single list.
# Lets add names so that we know who is what height.
# Do not forget to put a comma between each item.

fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [38]:
# We can create sub-lists for each family member instead.
# Notice that each sub-list is contained within its own set of [].

fam2 = [['liz', 1.73],
        ['emma', 1.68],
        ['mom', 1.71],
        ['dad', 1.89]]
fam2

[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]

In [39]:
# We can again confirm this type.

print(type(fam))
print(type(fam2))

<class 'list'>
<class 'list'>


### **Try the following problem #8**

## **List Subsetting and Slicing**

We can select different components of a list through subsetting. Remember that in Python, positions start with 0. To select the height of emma from the list fam, see below. Remember, emma's height is the 4th element of the list, so you must reference location 3.

In [41]:
fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam[3]

1.68

You can also count backwards with negative indexing. When counting backwards index positions start with -1. We no longer start at 0. To select the word 'dad' using backward indexing, we must reference position -2. You can use either form of subsetting at any time.

In [42]:
fam[-2]

'dad'

If we want to select multiple elements from a list and creating a new list, we can use list slicing. List slicing involves selecting a range of entries rather than just a single entry. This is done with a colon. (ie. **fam[3:5]**). **fam[3:5]** will select the 4th and 5th element, or the elements at index 3 and 4. Remember the ending index position is not selected, but is where a selection ends.

**[start (inclusive) : end (exclusive)]**

In [43]:
fam[3:5]

[1.68, 'mom']

In [44]:
# You can start a slice from index zero if you leave out the first value.

fam[:4]

['liz', 1.73, 'emma', 1.68]

In [45]:
# If you leave out the ending element, you include all elements up to and including the last item.

fam[5:]

[1.71, 'dad', 1.89]

### **Try problem #9**

### **Try problem #10**

### **Try problem #11**

## **List Manipulation**

Changing list elements by adding, subtracting, and replacing list elements.

In [49]:
# Consider that your dad is really 1.6 meters rather than 1.89.

fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam[7] = 1.86
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [50]:
# You can change liz and her height in one step as well.

fam[0:2] = ['lisa', 1.74]
fam

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [51]:
# We can also add items to a list, but it will not be permanent.

fam + ['me', 1.75]

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.75]

In [52]:
# To permanently alter the list, create a new list variable.

print(fam)
fam_ext = fam + ['me', 1.75]
fam_ext

['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]


['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.75]

In [53]:
# We must use del to delete elements from a list.

del(fam[2])
fam

['lisa', 1.74, 1.68, 'mom', 1.71, 'dad', 1.86]

In [54]:
# If we rerun the del code, we now remove emma's height.

del(fam[2])
fam

['lisa', 1.74, 'mom', 1.71, 'dad', 1.86]

In [55]:
# Just copying a list does not create two separate lists.

x = ['a', 'b', 'c']
y = x
y[1] = 'z'
print(y)
print(x)

['a', 'z', 'c']
['a', 'z', 'c']


In [56]:
# If you want y to represent a new list, we must specify this.

x = ['a', 'b', 'c']
y = list(x)
y[1] = 'z'
print(y)
print(x)

['a', 'z', 'c']
['a', 'b', 'c']


### **Try problem #12**

### **Try problem #13**

## **Functions & Methods**

A function is a piece of reusable code used for solving a particular task. For example, consider your list **fam = [1.73, 1.68, 1.71, 1.89]**. You can use a built in function to find the max value with the code **max(fam)**. We can also create our own functions for specialized tasks.

In [60]:
fam = [1.73, 1.68, 1.71, 1.89]
max(fam)

1.89

In [61]:
# We can also assign the output to a new variable

tallest = max(fam)
tallest

1.89

In [62]:
# Some functions accept additional options.
# How many digits do we want to round a value to?

print(round(1.68, 1)) # 1 decimal point
print(round(1.68, 0)) # 0 decimal points

1.7
2.0


In [63]:
# What if we don't include a second input value?
# Python will round to the closest integer.

round(1.68)

2

In [64]:
# How can we know what inputs a function takes?
# Here, number is required, [, ndigits] is optional. Arguments within [ ] are optional.

help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



### **Try problem #14**

### **Try problem #15**

A method is a function that 'belongs' to a Python object. For example, a a string object has methods of **capitalize()** or **replace()**, whereas floats have methods of **bit_length()** or **conjugate()**.

In [67]:
# Suppose we want the index of 'mom' from our fam list.
# We use dot notation here.

fam = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
fam.index('mom')

4

In [68]:
# How many times does an observation occur?
# Lets look at 1.73.

fam.count(1.73)

1

In [69]:
# Let us look at a few string (str) methods now.

sister = 'amy'
sister.capitalize()

'Amy'

In [70]:
# We can replace items as well.

sister.replace('y', 'iee')

'amiee'

In [71]:
# remember that unless we make a new variable, sister does not permanently change.

sister

'amy'

In [72]:
# Certain methods can be applied to different object types.
# For example, index can be applied to a string and a list.

print(sister.index('m')) # index of element in string
print(fam.index('mom')) # index of item in list

1
4


In [73]:
# Some methods DO change the object without creating a new variable.

print(fam)
fam.append('me')
print(fam)
fam.append('1.82')
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me']
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', '1.82']


### **Try problem #16**

### **Try problem #17**

### **Try problem #18**

## **Python Packages**

Functions and methods are extremely powerful. Because there are so many different functions and methods already created for Python, it is not possible to load everyone into each program that you are writing. Instead, we use Python packages to load what we actually need. The most common packages that we will use are Numpy, pandas, and Matplotlib, among many others. We use Anaconda or Google Colab because most of the necessary packages you will use are already included, you just have to load them. If you do come across a package that you want to use but it is not included, you can install additional packages. 

In [78]:
# Importing packages is easy and we often give packages shorter names.
# Lets import Numpy and rename it to np.

import numpy as np

In [79]:
# We now reference np before any of the Numpy functions.

np.array([1, 2, 3])

array([1, 2, 3])

In [80]:
# What if we only want to import one specific function from a package?

from numpy import array

array([1, 2, 3])

array([1, 2, 3])

### **Try problem #19**

## **Numpy**

https://numpy.org

Lists are very powerful and allow us to:
- collect variables
- hold different types
- change, add, and remove values

But lists do not allow us to carry out mathematical operations over the entirely list quickly. Lets look at an example.

In [82]:
# Lets combine our list of height and weight into bmi with bmi = weight / height ** 2
# Will element wise math work here?

height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

bmi = weight / height ** 2
bmi

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [83]:
# Numpy stands for numeric Python and provides us with the Numpy array.
# We can use these to perform calculations over entire arrays.

import numpy as np

np_height = np.array(height)
np_weight = np.array(weight)

bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

Although there are clear benefits to using a Numpy array. Be aware that Numpy arrays can only contain one type. For example, you cannot combine strings and floats as we did with our list of family heights. If we do include multiple types, Numpy will tranform all of the variable types to one type, strings.

Because Numpy arrays are just another Python type (similar to lists or float). This means it has its own set of methods that may behave differently that you expect.

In [84]:
# Consider how list and Numpy array methods behave differently.
# Remember that a Numpy array does element wise math.

python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

print(python_list + python_list)
print(numpy_array + numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [85]:
# Numpy arrays allow us to subset differently as well.

numpy_array_big = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

numpy_array_big > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [86]:
# We can even use this boolean array to do subsetting.
# This returns only those observations where the boolean is 'True'.

numpy_array_big[numpy_array_big > 4]

array([ 5,  6,  7,  8,  9, 10])

### **Try problem #20**

### **Try problem #21**

### **Try problem #22**

### **Try problem #23**

### **Try problem #24**

## **2D Numpy Arrays**

When we look at the original Numpy arrays we started with, **np_height** and **np_weight** they were of type **numpy.ndarray**. The ndarray portion stands for n dimensional array, where these two arrays are 1 dimensional. It is possible to create n dimensional arrays. Let us start with a 2D Numpy array.

In [93]:
# Lets create a 2D Numpy array.
# Notice the double set of [[]] below.

import numpy as np

np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [94]:
# We can see its shape or dimension through the array attribute.
# Remember that methods use (), but attributes do not.
# It should be 2 rows x 5 columns.

np_2d.shape

(2, 5)

In [95]:
# What happens if we change one float from the array to a string?
# They all become strings because Numpy arrays must contain only one data type.

np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, '88.4', 68.7]])
np_2d

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

Subsetting 2D Numpy arrays allows for greater flexibility. Suppose you want the entire first row. We can subset that with **np_2d[0]**. What if we want the 3rd element in the first row? We must subset the row and then the column with **np_2d[0][2]**. An alternative method is with a single set of brackets and a comma with **np_2d[0,2]**. Lets see this in action.

In [96]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

print(np_2d[0][2])
print(np_2d[0,2])

1.71
1.71


In [97]:
# Select the height and weight of the 2nd and 3rd family member.
# You want both rows and you only want the 2nd and 3rd column.
# This selects all rows, but only the 2nd and 3rd column.

np_2d[:,1:3] 

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [98]:
# We can also select the weight of all family members.
# This selects only the 2nd row, but all columns.

np_2d[1,:] 

array([65.4, 59.2, 63.6, 88.4, 68.7])

### **Try problem #25**

### **Try problem #26**

### **Try problem #27**

## **Numpy: Basic Statistics**

The first step to analysis is getting to know your data. What if our data contains 100 observations, or 1,000 observations? It becomes more difficult to understand the data without some form of analysis. We will start by looking at descriptive statistics. We often use descriptive statistics to determine if our data looks as we expect it to. For example, what if the average weight of our baseball player data is 2,000 pounds? Does that seem accurate?

In [104]:
# Lets start by looking at the average (mean) value of weight in our baseball data.
# Remember that weight is the second column.
# This is a numpy function, so remember to import numpy if you haven't before.

import numpy as np

baseball = [[74, 180, 23.87],
            [74, 215, 21.96],
            [72, 210, 29.76],
            [72, 210, 22.88],
            [73, 188, 27.54],
            [69, 176, 41.91],
            [69, 209, 19.98],
            [71, 200, 24.55],
            [76, 231, 24.91],
            [71, 180, 28.23],
            [73, 188, 29.17],
            [73, 180, 24.69],
            [74, 185, 21.83],
            [74, 160, 22.76],
            [69, 180, 25.12]]

np_baseball = np.array(baseball)
np.mean(np_baseball[:,1])            

192.8

In [105]:
# What is the median weight?

np.median(np_baseball[:,1])

188.0

In [106]:
# There are additional descriptive statistics as well.
# We can look at the correlation between two or more variables.
# Lets look at height and weight.

np.corrcoef(np_baseball[:,0], np_baseball[:,1])

array([[1.        , 0.20330919],
       [0.20330919, 1.        ]])

In [107]:
# We can generate data as well.
# Specify the mean, standard deviation, and number of samples you want.
# We will round everything to 2 decimal places.

height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
height

array([1.9 , 1.25, 1.7 , ..., 1.93, 1.75, 1.98])

In [108]:
# We can create full datasets in this way as well.

weight = np.round(np.random.normal(60.32, 15, 5000), 2)
person = np.column_stack((height, weight))
person

array([[ 1.9 , 68.02],
       [ 1.25, 70.91],
       [ 1.7 , 55.16],
       ...,
       [ 1.93, 67.6 ],
       [ 1.75, 60.09],
       [ 1.98, 72.31]])

### **Try problem #28**

### **Try problem #29**