# **Solutions**
- Run this cell before starting the notebook. You do not need to look at or understand the code. By running this, you will allow yourself to see solutions throughout the notebook as I ask you to solve problems.

In [31]:
%%capture
%load_ext autoreload
%autoreload 2

!pip install --upgrade git+https://github.com/MTSUDataScience/DATA3500.git

from course_solutions.Data3500_ICPS import *

### **Try the following problem #1**

Suppose you have 100, which you can invest with a 10% return each year. After one year, it's worth 100 x 1.1 = 110, and after two years it's 100 x 1.1 x 1.1 = 121. How much money do you have after seven years?

If you want to see the solution to this problem, run the code **solution1_1()** in an empty cell.

In [2]:
# Try your answer to problem #1 here.
# Remember that you can get an answer by running solution1_1()
# You can run the solution code by removing the '#' below and
# then running this cell.

solution1_1()

The formula for this problem is: 100 * 1.1 ** 7
The answer to this problem is: 194.87171000000012


### **Try the following problem #2**

Can you have your solution state that this is the total after 7 years? Can you include a '$' in front of the amount?

If you want to see the solution to this problem, run the code **solution1_2()** in an empty cell.

In [3]:
# Try your answer to problem #2 here.
# Remember that you can get an answer by running solution1_2()
# You can run the solution code by removing the '#' below and
# then running this cell.

solution1_2()

The code you will want to type is: print('After 7 years I have $', (100 * 1.1 ** 7))
The answer to this problem is: After 7 years I have $ 194.87171000000012


### **Try the following problem #3**

Can you create a new variable called BMI with the solution? Why would you do this?
height = 1.79 
weight = 65.2 

If you want to see the solution to this problem, run the code **solution1_3()** in an empty cell.

In [32]:
# Try your answer to problem #3 here.
# Remember that you can get an answer by running solution1_3()
# You can run the solution code by removing the '#' below and
# then running this cell.

solution1_3()

The formula for this problem is: bmi = weight / height ** 2
The answer to this problem is: 20.348927936081896


### **Try the following problem #4**
Remember how we calculated the money you ended up with after 7 years of investing $100? You did something like:

$$100 * 1.1 ** 7$$

Instead of calculating the actual values, you can use variables instead. Create a **savings** variable which represents the $100 ou start with. It is up to you to create a new variable as well to represent the 1.1 growth multiplier and redo the calculation.

- Create a new variable called **savings** equal to the starting value of $100.
- Create a new variable called **growth_multiplier** equal to 1.1.
- Set the solution to a new variable called **result** and print out the value.

If you want to see the solution to this problem, run the code **solution1_4()** in an empty cell.

In [5]:
# Try your answer to problem #4 here.
# Remember that you can get an answer by running solution1_4()
# You can run the solution code by removing the '#' below and
# then running this cell.

solution1_4()

Create savings with the code savings = 100
Create growth_multiplier with the code growth_multiplier = 1.1
Create result with the code results = savings * growth_multiplier ** 7

The value of result is: 194.87171000000012


### **Try the following problem #5**
We will work with other data types now, including strings and booleans.

- Create a new string called **desc** with the value 'compond interest'.
- Create a new boolean called **profitable** with the value 'True'.

If you want to see the solution to this problem, run the code **solution1_5()** in an empty cell.

In [6]:
# Try your answer to problem #5 here.
# Remember that you can get an answer by running solution1_5()
# You can run the solution code by removing the '#' below and
# then running this cell.

solution1_5()

Create desc with the code desc = 'compound interest'
Create profitability with the code profitability = 'True'

desc is equal to: compound interest
profitability is equal to: True


### **Try the following problem #6**
Remember that different types behave differently in Python. For example, when you sub two strings together you will get a different behavior than when you sum to integers.

- Calculate the product of **savings** and **growth_multiplier** and store the result in a new variable called **year1**.
  - The value of **savings** and **growth_multiplier** come from your previous solutions.
- What do you think the resulting type will be? Find out by printing the type of **year1**.
- Calculate the sum of **desc** and **desc** and store the result in a new variable called **doubledesc**.
- Print out **doubledesc**. Did you expect this?

If you want to see the solution to this problem, run the code **solution1_6()** in an empty cell.

In [7]:
# Try your answer to problem #6 here.
# Remember that you can get an answer by running solution1_6()
# You can run the solution code by removing the '#' below and
# then running this cell.

solution1_6()

Calculate year1 as year1 = savings * growth_multiplier
Check the type of year1 with print(type(year1))
Calculate doubledesc as doubledesc = desc + desc
Display the value of doubledesc with print(doubledesc)

year1 is type: <class 'float'>
doubledesc is equal to: compound interestcompound interest


### **Try the following problem #7**
Use the + operator to paste two strings together. Suppose you want to summarize the results of your investment with a string of text. Assuming you have defined **savings** and **result** before.

print('I started with' + savings + ' and now have' + result + '.')

Although this might seem like it will you, you will receive an error because you cannot sum strings and floats or integers. However, you can fix this by converting **savings** and **result** to string variables with the **str()** command. For example, you can convert **savings** to a string with **str(savings)**.

Similar functions include **int()**, **float()**, and **bool()**.

- Fix the print statement ('I started with' + savings + ' and now have' + result + '.')
- Convert the variable **pi_string** (already created for you below) to a float and store this as a new variable **pi_float**.

If you want to see the solution to this problem, run the code **solution1_7()** in an empty cell.

In [33]:
# Try your answer to problem #7 here.
# Remember that you can get an answer by running solution1_7()
# You can run the solution code by removing the '#' below and
# then running this cell.

pi_string = '3.1415926'

solution1_7()

The fix is: 'I started with ' + str(savings) + ' and now have ' + str(result) + '.'
The output will now look like: I started with 100 and now have 194.87171000000012.

Convert pi_string to a float with: pi_float = float(pi_string)
You can check the type of pi_float with: print(type(pi_float))

pi_float is of type: <class 'float'>


### **Try the following problem #8**
Lists can contain variables that reference other values as well.
- Create a list of lists with the following items and their area in square meters.
  - hallway
  - kitchen
  - living room
  - bedroom
  - bathroom
- Rather than putting the value of each room directly into the list, create a new set of variables with each room size.
  - hall = 11.25
  - kit = 18.0
  - liv = 20.0
  - bed = 10.75
  - bath = 9.50
- Print your new list.

Don't get confused: 'hallway' is a string and **hall** is a variable that represents the size of the hallway or 11.25.

If you want to see the solution to this problem, run the code **solution1_8()** in an empty cell.

In [9]:
# Try your answer to problem #8 here.
# Remember that you can get an answer by running solution1_8()
# You can run the solution code by removing the '#' below and
# then running this cell.

solution1_8()

Create the room size variables one at a time as: hall = 11.25, kit = 18.0, liv = 20.0, bed = 10.75, bath = 9.5
Create the list of lists as: house = [["hallway", hall],["kitchen", kit],"living room", liv],["bedroom", bed],["bathroom", bath]]

Printing the new list displays: [['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
The type of house is: <class 'list'>


### **Try the following problem #9**
Let us return to our list of rooms and sizes. I have recreated the list below called **areas**.

- Print out the second element from the **areas** list.
- Subset and print out the last element of the **areas** list using negative indexing.
- Select the number representing the area of the living room and print it out.

If you want to see the solution to this problem, run the code **solution1_9()** in an empty cell.

In [10]:
# Try your answer to problem #9 here.
# Remember that you can get an answer by running solution1_9()
# You can run the solution code by removing the '#' below and
# then running this cell.

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

solution1_9()

Select and print the second element with: print(areas[1])
Print the last element from the list with: print(areas[-1])
Print the area of the living room with: print(areas[5])

The second element is: 11.25
The last element is: 9.5
The area of the living room is: 20.0


### **Try the following problem #10**
Let us return to our list of rooms and sizes. I have recreated the list below called **areas**.

After extracting elements from a list you can perform additional calculations. For example, extracting the second and fourth element from the list **x** and pasting them together with the **+** operator is possible:

**x = ['a', 'b', 'c', 'd']**

**print(x[1] + x[2])**

- Using list subsetting and variable assignment, create a new variable, **eat_sleep_areas** that contains the sum of the area of the kitchen and the area of the bedroom.
- Print the new variable.

If you want to see the solution to this problem, run the code **solution1_10()** in an empty cell.

In [11]:
# Try your answer to problem #10 here.
# Remember that you can get an answer by running solution1_10()
# You can run the solution code by removing the '#' below and
# then running this cell.

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

solution1_10()

Create and sum your new variable with: eat_sleep_areas = areas[3] + areas[-3]
You do not have to use backwards indexing if you do not want to.
Print your new variable with: print(eat_sleep_areas)

The new variable should look like: 28.75


### **Try the following problem #11**
Let us return to our list of rooms and sizes. I have recreated the list below called **areas**.

- Use slicing to createa a list called **downstairs** that contains the first six elements of **areas**.
- Do a similar thing to create a new variable **upstairs** that contains the last 4 elements of **areas**.
- Print both **downstairs** and **upstairs**.

If you want to see the solution to this problem, run the code **solution1_11()** in an empty cell.

In [12]:
# Try your answer to problem #11 here.
# Remember that you can get an answer by running solution1_11()
# You can run the solution code by removing the '#' below and
# then running this cell.

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

solution1_11()

One solution to creating downstairs is: downstairs = areas[0:6]
Another solution is: downstairs = areas[:6]
One solution to creating upstairs is: upstairs = areas[6:10]
Another solution is: upstairs = areas[6:]
One final option is: upstairs = areas[-4:]

Downstairs should look like: ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
Upstairs should look like: ['bedroom', 10.75, 'bathroom', 9.5]


### **Try the following problem #12**
Let us return to our list of rooms and sizes. I have recreated the list below called **areas**.

- Update the area of the bathroom to be 10.50 instead of 9.50.
- Make the **areas** list more informative by chaning 'bedroom' to 'master bedroom'

If you want to see the solution to this problem, run the code **solution1_12()** in an empty cell.

In [34]:
# Try your answer to problem #12 here.
# Remember that you can get an answer by running solution1_12()
# You can run the solution code by removing the '#' below and
# then running this cell.

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

solution1_12()

We can correct bathroom with: areas[-1] = 10.50
We can change bedroom to master bedroom with: areas[6] = 'master bedroom'

Our new list looks like: ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'master bedroom', 10.75, 'bathroom', 10.5]


### **Try the following problem #13**
Let us return to our list of rooms and sizes. I have recreated the list below called **areas**.

- Use the **+** operator to paste the list **['poolhouse', 24.5]** to the end of **areas** and store the result as **areas_1**.

- Further extend **areas_1** by adding data on your garage. Add the string **'garage'** and float **15.45** to a new list **areas_2**.

If you want to see the solution to this problem, run the code **solution1_13()** in an empty cell.

In [35]:
# Try your answer to problem #13 here.
# Remember that you can get an answer by running solution1_13()
# You can run the solution code by removing the '#' below and
# then running this cell.

areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

solution1_13()

You can add the elements with: areas_1 = areas + ['poolhouse', 24.5]
You can add the garage elements with: areas_2 = areas_1 + ['garage', 15.45

areas_1 now looks like: ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5, 'poolhouse', 24.5]
areas_2 now looks like: ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5, 'poolhouse', 24.5, 'garage', 15.45]


### **Try the following problem #14**
Let us become more familiar with built in Python functions.
- Use **print()** in combination with **type()** to print out the type of **var1**.
- Use **len()** to get the length of the list **var1**. Wrap it in a **print()** function to print it out.
- Use **int()** to convert **var2** to an integer and store it as **out2**.

If you want to see the solution to this problem, run the code **solution1_14()** in an empty cell.

In [36]:
# Try your answer to problem #14 here.
# Remember that you can get an answer by running solution1_14()
# You can run the solution code by removing the '#' below and
# then running this cell.

var1 = [1, 2, 3, 4]
var2 = True

solution1_14()

You can use print and type together as: print(type(var1))
You can use len and print together as: print(len(var1))
You can create out2 as: out2 = int(var2)

The solution to print and type is: <class 'list'>
The solution to len and print is: 4
out2 is: 1


### **Try the following problem #15**
Let us become even more familiar with built in Python functions.

Look at the documentation of **sorted()** by typing **help(sorted)**. You will see that **sorted()** takes three arguments: **iterable, key** and **reverse**.

**key=None** means that if you don't specify the **key** argument, it will be **None**. **reverse=False** means that if you don't specify the **reverse** argument, it will be **False**.

- Use **+** to merge the contents of **first** and **second** into a new list **full**.
- Call **sorted()** on **full** and specify the **reverse** argument to be **True**. Save the sorted list as **full_sorted**.
- Print **full_sorted**.

If you want to see the solution to this problem, run the code **solution1_15()** in an empty cell.

In [37]:
# Try your answer to problem #15 here.
# Remember that you can get an answer by running solution1_15()
# You can run the solution code by removing the '#' below and
# then running this cell.

first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

solution1_15()

You can create full as: full = first + second
You can sort full as: full_sorted = sorted(full, reverse = True)
You can print full_sorted with: print(full_sorted)

full looks like: [11.25, 18.0, 20.0, 10.75, 9.5]
full_sorted becomes: [20.0, 18.0, 11.25, 10.75, 9.5]


### **Try the following problem #16**
We will now focus on working with methods. As a reminder, we can always type **help(str)** for assistance.
- Use the **upper()** method on **place** and store the results in **place_up**.
- Print out **place** and **place_up**. Did both change?
- Print out the number of o's on the variable **place** by calling **count()** on **place** and passing the letter **'o'** as in input to the method. We are talking about the variable **place**, not the word 'place'.

If you want to see the solution to this problem, run the code **solution1_16()** in an empty cell.

In [17]:
# Try your answer to problem #16 here.
# Remember that you can get an answer by running solution1_16()
# You can run the solution code by removing the '#' below and
# then running this cell.

place = 'poolhouse'

solution1_16()

We can use upper() by: place_up = place.upper()
we can print each variable with: print(place) and print(place_up)
We can calculate the number of o's with: print(place.count('o'))

The use of upper results in: POOLHOUSE
place looks like: poolhouse
place_up looks like: POOLHOUSE
The number of o's in place is: 3


### **Try the following problem #17**
We will continue working with methods. We will use **index()** to get the index of the first element of a list that matches its input and **count()** to get the number of times an element appears in a list.
- Use the **index()** method to get the index of the element in areas that is equal to **20.0**. Print out this index.
- Call **count()** on **areas** to find out how many times **9.50** appears in the list. Print this out as well.

If you want to see the solution to this problem, run the code **solution1_17()** in an empty cell.

In [18]:
# Try your answer to problem #17 here.
# Remember that you can get an answer by running solution1_17()
# You can run the solution code by removing the '#' below and
# then running this cell.

areas = [11.25, 18.0, 20.0, 10.75, 9.50] 

solution1_17()

We can obtain index of value 20 with: print(areas.index(20.0))
We can count how often 9.50 appears with: print(areas.count(9.50))

The index of 20.0 is: 2
The number of times 9.50 appears is: 1


### **Try the following problem #18**
We will continue working with methods. 
- Use **append()** twice to add the size of the poolhouse and the garage again. The poolhouse area is 24.5 and the garage area is 15.45.
- Print out **areas**.
- Use the **reverse()** method to reverse the order of the elements in **areas**.
- Print out **areas** again.

If you want to see the solution to this problem, run the code **solution1_18()** in an empty cell.

In [19]:
# Try your answer to problem #18 here.
# Remember that you can get an answer by running solution1_18()
# You can run the solution code by removing the '#' below and
# then running this cell.

areas = [11.25, 18.0, 20.0, 10.75, 9.50]

solution1_18()

We can append the first value with: areas.append(24.5)
We append the second value with: areas.append(15.45
We print this list with: print(areas)
We reverse the order of the list with: areas.reverse()
We print the list again wtih: print(areas)

After appending both values, areas becomes: [11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
After reversing the oder we have: [15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


### **Try the following problem #19**
We will now work with importing packages. If we want to know the circumference, **C**, and area, **A**, of a circle when the radius of the circle is **r**, you can calculate **C** and **A** as:
$$C = 2(pi)r$$
$$A = (pi)r^2$$
But how we do get the value of **pi**? We can use the **math** package.
- Import the **math** package. Now you can access the constant **pi** with **math.pi**.
- Calculate the circumference of the circle and store it in **C**.
- Calculate the area of the circle and store it in **A**.
- Print both values.

If you want to see the solution to this problem, run the code **solution1_19()** in an empty cell.

In [20]:
# Try your answer to problem #19 here.
# Remember that you can get an answer by running solution1_19()
# You can run the solution code by removing the '#' below and
# then running this cell.

r = 0.43

solution1_19()

We import the math package with: import math
We calculate C with: C = 2 * r * math.pi
We calculate A with: A = math.pi * r ** 2

The value of C is: 2.701769682087222
The value of A is: 0.5808804816487527


### **Try the following problem #20**
A list of **baseball** is provided as the height of some baseball players in centimeters.
- Import the **numpy** package as **np** so that you can refere to **numpy** with **np**.
- Use **np.array()** to create a **numpy** array from **baseball**. Name this array **np_baseball**.
- Print out the type of **np_baseball**.

If you want to see the solution to this problem, run the code **solution1_20()** in an empty cell.

In [21]:
# Try your answer to problem #20 here.
# Remember that you can get an answer by running solution1_20()
# You can run the solution code by removing the '#' below and
# then running this cell.

baseball = [180, 215, 210, 210, 188, 176, 209, 200]    

solution1_20()

Import numpy with: import numpy as np
Create a numpy array as: np_baseball = np.array(baseball)
Print the type with: print(type(np_baseball))

np_baseball looks like: [180 215 210 210 188 176 209 200]
The type of np_baseball is: <class 'numpy.ndarray'>


### **Try the following problem #21**
Major League Baseball provides you with a larger list of player heights in inches. This data comes in the form of a regular Python list, **height_in**.
- Create a numpy array from **height_in** with the new name **np_height_in**.
- print **np_height_in**.
- Multiply **np_height_in** with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array called **np_height_m**.
- Print **np_height_m**.

If you want to see the solution to this problem, run the code **solution1_21()** in an empty cell.

In [22]:
# Try your answer to problem #21 here.
# Remember that you can get an answer by running solution1_21()
# You can run the solution code by removing the '#' below and
# then running this cell.

height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 
             74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 
             71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 
             74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 
             74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 
             78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 
             70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 
             74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 
             74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 
             75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 
             80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 
             74, 76, 76, 74, 73, 74, 70, 72]   

solution1_21()   

Create a Numpy array with: np_height_in = np.array(height_in)
We print this new array with: print(np_height_in
Convert this array to meters with: np_height_m = np_height_in * 0.0254
We print the final array with: print(np_height_m)

np_height_in as a Numpy array looks like:
[74 74 72 72 73 69 69 71 76 71 73 73 74 74 69 70 73 75 78 79 76 74 76 72
 71 75 77 74 73 74 78 73 75 73 75 75 74 69 71 74 73 73 76 74 74 70 72 77
 74 70 73 75 76 76 78 74 74 76 77 81 78 75 77 75 76 74 72 72 75 73 73 73
 70 70 70 76 68 71 72 75 75 75 75 68 74 78 71 73 76 74 74 79 75 73 76 74
 74 73 72 74 73 74 72 73 69 72 73 75 75 73 72 72 76 74 72 77 74 77 75 76
 80 74 74 75 78 73 73 74 75 76 71 73 74 76 76 74 73 74 70 72]
np_height_m as a Numpy array looks like:
[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778  1.8542 1.905  1.9812 2.0066
 1.9304 1.8796 1.9304 1.8288 1.8034 1.905  1.9558 1.8796 1.8542 1.8796
 1.9812 1.8542 1.905  1.8542 1.905  1.905  1

### **Try the following problem #22**
Major League Baseball also provides you with their weight data. Again, both are available as regular Python lists: **height_in** and **weight_lb**. **height_in** is in inches and **weight_lb** is in pounds.
- Create a numpy array from the **weight_lb** list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting **numpy** array as **np_weight_kg**.
- Use **np_height_m** and **np_weight_kg** to calculate player BMI.
$$BMI = weight(kg) / height(m)^2$$
and save the **numpy** array as **bmi**.
- Print **bmi**.

If you want to see the solution to this problem, run the code **solution1_22()** in an empty cell.

In [23]:
# Try your answer to problem #22 here.
# Remember that you can get an answer by running solution1_22()
# You can run the solution code by removing the '#' below and
# then running this cell.

height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 
             74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 
             71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 
             74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 
             74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 
             78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 
             70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 
             74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 
             74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 
             75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 
             80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 
             74, 76, 76, 74, 73, 74, 70, 72]   

weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180,
             188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 
             205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 
             200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 
             200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 
             200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 
             228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 
             211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 
             225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 
             200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 
             220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 
             213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 
             220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 
             198, 200, 195, 210, 220, 190, 210, 225, 180, 185] 

solution1_22()   

We create our new numpy array in meters as: np_height_m = np.array(height_in) * 0.0254
We create our new numpy array in kilograms as: np_weight_kg = np.array(weight_lb) * 0.453592
We create bmi as: bmi = np_weight_kg / np_height_m ** 2
We print our final bmi numpy array as: print(bmi)

np_height_m looks like:
[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778  1.8542 1.905  1.9812 2.0066
 1.9304 1.8796 1.9304 1.8288 1.8034 1.905  1.9558 1.8796 1.8542 1.8796
 1.9812 1.8542 1.905  1.8542 1.905  1.905  1.8796 1.7526 1.8034 1.8796
 1.8542 1.8542 1.9304 1.8796 1.8796 1.778  1.8288 1.9558 1.8796 1.778
 1.8542 1.905  1.9304 1.9304 1.9812 1.8796 1.8796 1.9304 1.9558 2.0574
 1.9812 1.905  1.9558 1.905  1.9304 1.8796 1.8288 1.8288 1.905  1.8542
 1.8542 1.8542 1.778  1.778  1.778  1.9304 1.7272 1.8034 1.8288 1.905
 1.905  1.905  1.905  1.7272 1.8796 1.9812 1.8034 1.8542 1.9304 1.8796
 1.8796 2.0066 1.905  1.8542 1.9304 1.8796 1.8796 1.

### **Try the following problem #23**
Major League Baseball wants you to identify all lightweight baseball players (ie. those with a bmi below 21).
- Create a boolean **numpy** array: the element of the array should be **True** if the corresponding baseball player's BMI is below 21. You can use the **<** operator for this. Name the new array **light**.
- Print the array **light**.
- Print out a **numpy** array with the BMIs of all baseball players whose BMI is below 21. Use **light** inside square brackets to do a selection on the **bmi** array.

If you want to see the solution to this problem, run the code **solution1_23()** in an empty cell.

In [24]:
# Try your answer to problem #23 here.
# Remember that you can get an answer by running solution1_23()
# You can run the solution code by removing the '#' below and
# then running this cell.

height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 
             74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 
             71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 
             74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 
             74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 
             78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 
             70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 
             74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 
             74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 
             75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 
             80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 
             74, 76, 76, 74, 73, 74, 70, 72]   

weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180,
             188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 
             205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 
             200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 
             200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 
             200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 
             228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 
             211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 
             225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 
             200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 
             220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 
             213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 
             220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 
             198, 200, 195, 210, 220, 190, 210, 225, 180, 185] 

solution1_23()   

We convert our height list to a Numpy array in meters with: np_height_m = np.array(height_in) * 0.0254
We convert our weight list to a Numpy array in kgs with: np_weight_kg = np.array(weight_lb) * 0.453592
Create our bmi array with: bmi = np_weight_kg / np_height_m ** 2
Create light with: light = bmi < 21
Print light with: print(light)
Subset bmi with light and print with: print(bmi[light])

light looks like:
[False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True False False False False False False
 Fa

### **Try the following problem #24**
- Subset **np_weight_lb** by printing out the element at index 50. Remember we want the observation at index 50, not at the 50th spot. These are different because we use zero indexing (ie. the first observation is located at index 0).
- Print out a sub-array of **np_height_in** that contains elements at index 100 up to *and including* index 110. Remember that the second number in your sub-array range is not included in the final sub-array.

If you want to see the solution to this problem, run the code **solution1_24()** in an empty cell.

In [25]:
# Try your answer to problem #24 here.
# Remember that you can get an answer by running solution1_24()
# You can run the solution code by removing the '#' below and
# then running this cell.

height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 
             74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 
             71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 
             74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 
             74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 
             78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 
             70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 
             74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 
             74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 
             75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 
             80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 
             74, 76, 76, 74, 73, 74, 70, 72]   

weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180,
             188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 
             205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 
             200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 
             200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 
             200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 
             228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 
             211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 
             225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 
             200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 
             220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 
             213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 
             220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 
             198, 200, 195, 210, 220, 190, 210, 225, 180, 185] 

solution1_24()  

We convert our height list to a Numpy array with: np_height_m = np.array(height_in)
We convert our weight list to a Numpy array iwith: np_weight_kg = np.array(weight_lb)
We print out weight at index 50 with: print(np_weight_lb[50]
We print a sub-array that contains elements at index 100 up to and including index 100 with: print(np_height_in[100:111]

index 50 looks like:
200
sub-array 100 through 110 looks like:
[73 74 72 73 69 72 73 75 75 73 72]


### **Try the following problem #25**
Lets start with a list of lists which contains 4 elements. Each element is a list containing the height and weight of 4 baseball players. **baseball** is already created for you.
- Use **np.array()** to create a 2D **numpy** array from **baseball**. Name it **np_baseball**.
- Print out the type of **np_baseball**.
- Print out the **shape** attribute of **np_baseball**. Use **np_baseball.shape**.

If you want to see the solution to this problem, run the code **solution1_25()** in an empty cell.

In [26]:
# Try your answer to problem #25 here.
# Remember that you can get an answer by running solution1_25()
# You can run the solution code by removing the '#' below and
# then running this cell.

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]               

solution1_25()  

We create np_baseball with: np_baseball = np.array(baseball)
We can print the type of np_baseball with: print(type(np_baseball))
We can see the shape of np_baseball with: print(np_baseball.shape)

np_baseball as a Numpy array looks like:
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
The type of np_baseball is: <class 'numpy.ndarray'>
The shape of np_baseball is: (4, 2)


### **Try the following problem #26**
The MLB has provided us with a Python list of lists that contains the height and weight 15 baseball players. This list of lists is provided as **baseball**.
- Use **np_array()** to create a 2D **numpy** array from **baseball**. Name it **np_baseball**. Remember how to extract elements from a **numpy** array. For example, x = [['a', 'b'], ['c', 'd']]. To extract element 'c' and 'd', we can use np_x = [:,0].
- Print out the **shape** attribute of **np_baseball**.
- Print out the the 8th row of **np_baseball**.
- Make a new variable, **np_weight_lb**, containing the entire second column of **np_baseball**.
- Select the height (first column) of the 12th baseball player in **np_baseball** and print it out.

If you want to see the solution to this problem, run the code **solution1_26()** in an empty cell.

In [27]:
# Try your answer to problem #26 here.
# Remember that you can get an answer by running solution1_26()
# You can run the solution code by removing the '#' below and
# then running this cell.

baseball = [[74, 180],
            [74, 215],
            [72, 210],
            [72, 210],
            [73, 188],
            [69, 176],
            [69, 209],
            [71, 200],
            [76, 231],
            [71, 180],
            [73, 188],
            [73, 180],
            [74, 185],
            [74, 160],
            [69, 180]]             

solution1_26()  

We create np_baseball with: np_baseball = np.array(baseball)
We can see the shape of np_baseball with: print(np_baseball.shape)
We can print the 8th row with: print(np_baseball[7,:])
We can select the entire 2nd column with: np_weight_lb = np_baseball[:,1]
We can print the heiht of the 12th player with: print(np_baseball[11,0])

np_baseball as a Numpy array looks like:
[[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 188]
 [ 69 176]
 [ 69 209]
 [ 71 200]
 [ 76 231]
 [ 71 180]
 [ 73 188]
 [ 73 180]
 [ 74 185]
 [ 74 160]
 [ 69 180]]
The shape of np_baseball is: (15, 2)
The 8th row looks like: [ 71 200]
The second column looks like:
[180 215 210 210 188 176 209 200 231 180 188 180 185 160 180]
The height of the 12th player is: 73


### **Try the following problem #27**
We can apply arithmetic to 2D arrays just as easily as we did for a 1D array. **baseball** now contains a 3rd column for age.
- We now have a a 2D **numpy** array called **updated** that contains the change in height, weight, and age of all baseball players in our **baseball** list of lists. Add **np_baseball** and **updated** together than print the result.
- You want to convert the units of height and weight to metric. As a first step, create a **numpy** array with three values: **0.0254**, **0.453592**, and **1**. Name this **conversion**.
- Multiply **np_baseball** with **conversion** and print the results.

If you want to see the solution to this problem, run the code **solution1_27()** in an empty cell.

In [28]:
# Try your answer to problem #27 here.
# Remember that you can get an answer by running solution1_27()
# You can run the solution code by removing the '#' below and
# then running this cell.

baseball = [[74, 180, 23.87],
            [74, 215, 21.96],
            [72, 210, 29.76],
            [72, 210, 22.88],
            [73, 188, 27.54],
            [69, 176, 41.91],
            [69, 209, 19.98],
            [71, 200, 24.55],
            [76, 231, 24.91],
            [71, 180, 28.23],
            [73, 188, 29.17],
            [73, 180, 24.69],
            [74, 185, 21.83],
            [74, 160, 22.76],
            [69, 180, 25.12]]

updated = [[1.2303559 , -11.16224898, 1],
           [1.02614252,  16.09732309, 1],
           [1.1544228 ,   5.08167641, 1],
           [1.42614252,   9.09732309, 1],
           [1.1244228 ,   5.08167641, 1],   
           [1.53614252,   6.09732309, 1],
           [1.1944228 ,   5.08167641, 1],   
           [1.86614252,  11.24732309, 1],
           [1.2244228 ,   5.26167641, 1],   
           [1.85614252,  14.09732309, 1],
           [1.1549278 ,   8.08167641, 1],   
           [1.02837593,  19.09732309, 1],
           [1.1775937 ,   1.98167641, 1],   
           [1.17393793,  17.37732309, 1],
           [1.1125222 ,   5.11167641, 1]]   

solution1_27()  

We create np_baseball with: np_baseball = np.array(baseball)
We create np_updated with: np_updated = np.array(updated)
We can see the addition with: print(np_baseball + updated)
We can create conversion with: conversion = np.array([0.0254, 0.453592, 1])
We can print the converted values with: print(np_baseball * conversion)

The new array after addition looks like:
[[ 75.2303559  168.83775102  24.87      ]
 [ 75.02614252 231.09732309  22.96      ]
 [ 73.1544228  215.08167641  30.76      ]
 [ 73.42614252 219.09732309  23.88      ]
 [ 74.1244228  193.08167641  28.54      ]
 [ 70.53614252 182.09732309  42.91      ]
 [ 70.1944228  214.08167641  20.98      ]
 [ 72.86614252 211.24732309  25.55      ]
 [ 77.2244228  236.26167641  25.91      ]
 [ 72.85614252 194.09732309  29.23      ]
 [ 74.1549278  196.08167641  30.17      ]
 [ 74.02837593 199.09732309  25.69      ]
 [ 75.1775937  186.98167641  22.83      ]
 [ 75.17393793 177.37732309  23.76      ]
 [ 70.1125222  185.11167641  26.12      ]]
T

### **Try the following problem #28**
After looking at the height, weight, and age data from **baseball**, you notice that some height values are abnormally high. Lets investigate.
- Create a **numpy** array **np_height_in** that is equal to the first column of **np_baseball**.
- Print out the mean of **np_height_in**.
- Print out the median of **np_height_in**.
If you want to see the solution to this problem, run the code **solution1_28()** in an empty cell.

In [29]:
# Try your answer to problem #28 here.
# Remember that you can get an answer by running solution1_28()
# You can run the solution code by removing the '#' below and
# then running this cell.

baseball = [[74, 180, 23.87],
            [74, 215, 21.96],
            [72, 210, 29.76],
            [72, 210, 22.88],
            [73, 188, 27.54],
            [9969, 176, 41.91],
            [69, 209, 19.98],
            [71, 200, 24.55],
            [76, 231, 24.91],
            [71, 180, 28.23],
            [73, 188, 29.17],
            [73, 180, 24.69],
            [74, 185, 21.83],
            [74, 160, 22.76],
            [69, 180, 25.12]]                        

solution1_28()  

We create np_height_in with: np_height_in = np_baseball[:,0]
We print the mean with: print(np.mean(np_height_in))
We print the median with: print(np.median(np_height_in))

The mean value is: 732.2666666666667
The median valie is: 73.0


### **Try the following problem #29**
Lets put everything we have learned so far together here. You have now received information from the MLS. They have provided you with two lists. **positions** contains player positions as **GK, M, A, D** for goalkeeper, midfield, attack, or defense. The second list, **heights**, contains the integer value for each players height in centimeters. You think that the median height of goalkeepers is higher than that of other players on the field. Are you right?
- Convert **height** and **positions**, which are regular lists, to numpy arrays and call them **np_heights** and **np_positions**.
- Extract all the heights of goalkeepers. You can use a little trick here: use the **np_positions == 'GK** as an index for **np_heights**. Assign the results to **gk_heights**.
- Extract the heights of all other players by using **np_positions != 'GK'** as an index for **np_heights** and assign this to **other_heights**.
- Print out the median height of the goalkeepers using **np.median()**.
- Do the same for the other positions.
If you want to see the solution to this problem, run the code **solution1_29()** in an empty cell.

In [30]:
# Try your answer to problem #29 here.
# Remember that you can get an answer by running solution1_29()
# You can run the solution code by removing the '#' below and
# then running this cell.

positions = ['GK', 'M', 'A', 'GK', 'GK', 'D', 'A', 'GK', 'D', 'M',
             'M', 'GK', 'A', 'A', 'A', 'D', 'D', 'M', 'D', 'A',
             'GK', 'A', 'M', 'M', 'D', 'A', 'M', 'D', 'A', 'M']
heights = [191, 187, 188, 194, 192, 190, 177, 187, 171, 159,
           185, 199, 185, 174, 177, 171, 159, 172, 171, 179,
           195, 185, 184, 188, 174, 179, 176, 168, 166, 161]  

solution1_29()  

We create np_positions with: np_positions = np.array(positions)
We create np_heights with: np_positions = np.array(heights)
We extract GK heights with: gk_heights = np_heights[np_positions =='GK']
We extract other heights with: other_heights = np_heights[np_positions !='GK']
We create and display GK median height with: print('Median height of goalkeepers: ' + str(np.median(gk_heights)))
We create and display other median height with: print('Median height of other: ' + str(np.median(other_heights)))

gk_heights looks like:
[191 194 192 187 199 195]
other_heights looks like:
[187 188 190 177 171 159 185 185 174 177 171 159 172 171 179 185 184 188
 174 179 176 168 166 161]
Median height of goalkeepers: 193.0
Median height of other: 176.5
